describe('Login', () => {

    it('Sign in', () => {
      cy.visit("https://finnewerpclient.azurewebsites.net/")
      cy.get('tenant-change > :nth-child(1) > a').click()
      cy.wait(5000)
      cy.get('.kt-switch > label > span').click()
      cy.get('#tenancyNameInput').type('TestC')
      cy.get('.btn-primary > span').click()
      cy.wait(10000)
      cy.get('.kt-form > :nth-child(1) > .form-control').type('admin')
      cy.get(':nth-child(2) > .form-control').type('123456')
      cy.get('.btn').click()
    })

    it.skip('Account Module/FinStat', () => {
      cy.get('.kt-menu__nav > :nth-child(3) > :nth-child(1) > .kt-menu__link-text').click()
      cy.get(':nth-child(2) > :nth-child(3) > .kt-menu__toggle > .kt-menu__link-text').click()
      cy.get('.kt-menu__item--open > .kt-menu__submenu > .kt-menu__subnav > :nth-child(10) > .kt-menu__link > .kt-menu__link-text').click()
      cy.get('#reportTilte').type('AutoTest2')
      cy.get('form.ng-touched > .row > .text-right > .form-group > .btn').click()
      cy.wait(10000)
      cy.contains('Property Definition').click()
      cy.get('.row.form-group > :nth-child(1) > form.ng-tns-c414-13 > :nth-child(1) > :nth-child(1) > .form-group > .form-control').select('general')
      cy.get('.ng-invalid.ng-dirty > :nth-child(1) > :nth-child(2) > .form-group > .form-control').select('Category Caption')
      cy.get('#caption').type('test1')
      cy.get('.ui-inputswitch-slider').click()
      cy.get('.col-md-12 > .form-group > .btn').click()
      cy.wait(10000)
      cy.get('.row.form-group > :nth-child(1) > form.ng-tns-c414-13 > :nth-child(1) > :nth-child(2) > .form-group > .form-control').select('Main Caption')
      cy.get('.row.form-group > :nth-child(1) > form.ng-tns-c414-13 > :nth-child(1) > :nth-child(3) > .form-group > .form-control').select('233').should('have.value','233')
      cy.get('#caption').type('Judo')
      cy.get('.ui-inputswitch-slider').click()
      cy.get('.col-md-12 > .form-group > .btn').click()
      cy.wait(10000)
      cy.contains('Account Mapping').click()
      cy.get('.kt-form > form.ng-tns-c414-13 > :nth-child(1) > :nth-child(1) > .form-group > .form-control').select('general')
      cy.wait(5000)
      cy.get('.kt-form > form.ng-tns-c414-13 > :nth-child(1) > :nth-child(2) > .form-group > .form-control').select('258').should('have.value', '258')
      cy.get('.kt-form > form.ng-tns-c414-13 > :nth-child(1) > :nth-child(3) > .form-group > .form-control').select('ACCRUED')
      cy.get('.col-sm-12 > .form-group > .btn').click()
    })

    it.skip('Account Module/ Default Account', () => {
      cy.get('.kt-menu__nav > :nth-child(3) > :nth-child(1) > .kt-menu__link-text').click()
      cy.get(':nth-child(2) > :nth-child(3) > .kt-menu__toggle > .kt-menu__link-text').click()
      cy.get(':nth-child(2) > .kt-menu__item--open > .kt-menu__submenu > .kt-menu__subnav > :nth-child(2) > .kt-menu__link > .kt-menu__link-text').click()
      cy.wait(5000)
      cy.get(':nth-child(1) > .form-group > .ng-select > .ng-select-container > .ng-clear-wrapper').click()
      cy.get(':nth-child(1) > .form-group > .ng-select > .ng-select-container > .ng-arrow-wrapper').click()
      cy.get(':nth-child(1) > .form-group > .ng-select').click()
      cy.get('.ng-dropdown-panel-items').contains('Sales').click()
      cy.get(':nth-child(2) > .form-group > .ng-select > .ng-select-container').click()
      cy.get('.ng-dropdown-panel-items').contains('ACCRUED').click()
      cy.get('.form-group > .btn').click()
      cy.wait(7000)
      cy.get('.btn-group > .dropdown-toggle').click()
      cy.get('.dropdown-menu').contains('Delete').click()
      cy.get('.swal2-confirm').click()
      cy.get(':nth-child(1) > .form-group > .ng-select > .ng-select-container').click()
      cy.get('.ng-dropdown-panel-items').contains('Expense').click()
      cy.get(':nth-child(2) > .form-group > .ng-select > .ng-select-container').click()
      cy.get('.ng-dropdown-panel-items').contains('ACCRUED ITF').click()
      cy.get('.form-group > .btn').click()
      cy.wait(10000)
      cy.get('.btn-group > .dropdown-toggle').click()
      cy.get('.dropdown-menu').contains('Edit').click()
      cy.get('.form-group > .btn').click()
      cy.wait(10000)
    })

    it.skip('Account Module/End Of Period' , () =>{
      cy.get('.kt-menu__nav > :nth-child(3) > :nth-child(1) > .kt-menu__link-text').click()
      cy.get(':nth-child(2) > :nth-child(3) > .kt-menu__toggle > .kt-menu__link-text').click()
      cy.get(':nth-child(2) > .kt-menu__item--open > .kt-menu__submenu > .kt-menu__subnav > :nth-child(3) > .kt-menu__link > .kt-menu__link-text').click()
      cy.wait(7000)
      cy.get('.form-group > .btn').click()
      cy.get('.swal2-confirm').click()
      cy.wait(7000)
      cy.get('.swal2-confirm').click()
    })

    it.skip('Account Module/Add COA' , () =>{
      cy.get('.kt-menu__nav > :nth-child(3) > :nth-child(1) > .kt-menu__link-text').click()
      cy.get(':nth-child(2) > :nth-child(3) > .kt-menu__toggle > .kt-menu__link-text').click()
      cy.get(':nth-child(2) > .kt-menu__item--submenu.kt-menu__item--open > .kt-menu__submenu > .kt-menu__subnav > :nth-child(1) > .kt-menu__link > .kt-menu__link-text').click()
      cy.wait(7000)
      cy.get('.kt-subheader__wrapper > .btn').click()
      cy.wait(2000)
      //change the input name//
      cy.get('#inputAcctName').type('Oboh Jude')
      //change the input value//
      cy.get('#inputCredit').type('3456665')
      cy.get(':nth-child(2) > :nth-child(1) > .form-group > .form-control').select('Asset')
      cy.get(':nth-child(2) > :nth-child(2) > .form-group > .form-control').select('Level2')
      cy.get('.col-md-12 > .form-group > .form-control').select('CONSUMABLES')
      cy.get('.ng-star-inserted.ng-dirty > .modal-footer > .btn-primary').click()
      cy.wait(5000)
    })

    it.skip('Account Module/Inactive Account',() => {
      cy.get('.kt-menu__nav > :nth-child(3) > :nth-child(1) > .kt-menu__link-text').click()
      cy.get(':nth-child(2) > :nth-child(3) > .kt-menu__toggle > .kt-menu__link-text').click()
      cy.get(':nth-child(2) > .kt-menu__item--submenu.kt-menu__item--open > .kt-menu__submenu > .kt-menu__subnav > :nth-child(1) > .kt-menu__link > .kt-menu__link-text').click()
      cy.wait(7000)
      cy.get(':nth-child(1) > :nth-child(1) > .btn-group > .dropdown-toggle').click()
      cy.get('.dropdown-menu > :nth-child(2) > .ng-tns-c340-13').click()
      cy.get('.swal2-confirm').click()
      cy.wait(7000)
      cy.get('.form-group > .btn').click()
    })

    it.skip('Account Module/Journal Entry', () => {
      cy.get('.kt-menu__nav > :nth-child(3) > :nth-child(1) > .kt-menu__link-text').click()
      cy.get(':nth-child(2) > :nth-child(4) > .kt-menu__toggle > .kt-menu__link-text').click()
      cy.get(':nth-child(2) > .kt-menu__item--open > .kt-menu__submenu > .kt-menu__subnav > :nth-child(4) > .kt-menu__link > .kt-menu__link-text').click()
      cy.wait(7000)
      cy.get(':nth-child(1) > :nth-child(1) > .form-group > .form-control').select('ACCRUED')
      cy.get('#SampleDatePicker').click()
      cy.get(':nth-child(2) > :nth-child(7) > span').click()
      cy.get('#inputDebit').type('500000')
      cy.get(':nth-child(2) > .col-md-6 > .form-group > .form-control').type('TestAuto')
      cy.get('.pull-right > .btn').click()
      cy.wait(5000)
      //not activated yet//
      /*cy.get('.primeng-datatable-container > .col-md-12 > :nth-child(1)').click()
      cy.wait(5000)*/
    })

    it.skip('Account Module/Reports/FinStat' , () => {
      cy.get('.kt-menu__nav > :nth-child(8) > :nth-child(1) > .kt-menu__link-text').click()
      cy.get('[kt-hidden-height="80"] > :nth-child(2) > .kt-menu__item--submenu > .kt-menu__toggle > .kt-menu__link-text').click()
      cy.get('[kt-hidden-height="80"] > :nth-child(2) > .kt-menu__item--submenu > .kt-menu__submenu > .kt-menu__subnav > :nth-child(2) > .kt-menu__link > .kt-menu__link-text').click()
      cy.wait(7000)
      cy.get('.form-group > :nth-child(1) > .form-control').select('First Year')
      cy.get(':nth-child(2) > .form-control').select('06-Apr-2021')
      cy.get('.pull-right > .btn').click()
      cy.wait(7000)
    })

    it.skip('Account Module/Report/General Ledger' , () => {
      cy.get('.kt-menu__nav > :nth-child(8) > :nth-child(1) > .kt-menu__link-text').click()
      cy.get('[kt-hidden-height="80"] > :nth-child(2) > .kt-menu__item--submenu > .kt-menu__toggle > .kt-menu__link-text').click()
      cy.get('[kt-hidden-height="80"] > :nth-child(2) > .kt-menu__item--submenu > .kt-menu__submenu > .kt-menu__subnav > :nth-child(3) > .kt-menu__link > .kt-menu__link-text').click()
      cy.wait(7000)
      cy.get(':nth-child(1) > .form-group > .form-control').select('ACCRUED')
      cy.get('#StartEndRangeEntityChange').click()
      cy.get(':nth-child(1) > bs-calendar-layout > .bs-datepicker-body > .days > tbody > :nth-child(2) > :nth-child(2) > span').click()
      cy.get(':nth-child(2) > bs-calendar-layout > .bs-datepicker-body > .days > tbody > :nth-child(2) > :nth-child(4) > span').click()
      cy.get('.pull-right > .btn').click()
      cy.wait(5000)
    })

    it.skip('Account Module/Report/Trial Balance' , () => {
      cy.get('.kt-menu__nav > :nth-child(8) > :nth-child(1) > .kt-menu__link-text').click()
      cy.get('[kt-hidden-height="80"] > :nth-child(2) > .kt-menu__item--submenu > .kt-menu__toggle > .kt-menu__link-text').click()
      cy.get('[kt-hidden-height="80"] > :nth-child(2) > .kt-menu__item--submenu > .kt-menu__submenu > .kt-menu__subnav > :nth-child(4) > .kt-menu__link > .kt-menu__link-text').click()
      cy.get('.col-lg-10 > .form-control').select('06-Apr-2021')
      cy.get('.col-lg-2 > .btn').click()
      cy.wait(20000)
    })
  })
